homepage: "https://docs.libra2.org"
language: rust
primary_contact: "info@aptoslabs.com"
main_repo: "https://github.com/libra2org/libra2-core"
auto_ccs:
  - "oss-fuzz-notifications@aptoslabs.com"
  - "security@aptoslabs.com"
sanitizers:
  - none
fuzzing_engines:
  - libfuzzer
coverage_extra_args: -ignore-filename-regex=.*/rustc/.*