name: "Get latest CreditChain CLI"
description: |
  Fetches the latest released CreditChain CLI.
inputs:
  destination_directory:
    description: "Directory to install the CLI in"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install CLI from CreditChain repository
      shell: bash
      run: |
        mkdir -p "${{ inputs.destination_directory }}"
        RUSTFLAGS="--cfg tokio_unstable" cargo install --locked --git https://github.com/ibankio/creditchain.git --profile cli libra2
        cp "$HOME/.cargo/bin/libra2" "${{ inputs.destination_directory }}/creditchain"
        chmod +x "${{ inputs.destination_directory }}/creditchain"
