# A simple composite action that checks if the calling repository is CreditChain
# There are some actions that should only be run on CreditChain, e.g. publishing or expensive cron jobs
inputs:
  cancel-workflow:
    description: "Cancel the workflow if the calling repository is not CreditChain"
    required: false
    default: false
  token:
    description: "The GitHub token to use"
    required: false
    default: ${{ github.token }}
outputs:
  is-creditchain:
    description: "Whether the calling repository is CreditChain"
    value: ${{ steps.determine-repo.outputs.is-creditchain }}
  is-creditchain-core:
    description: "Legacy alias for compatibility with older workflows"
    value: ${{ steps.determine-repo.outputs.is-creditchain }}
runs:
  using: composite
  steps:
    - name: Determine the calling repo
      id: determine-repo
      shell: bash
      run: |
        if [[ "${{ github.repository }}" == "ibankio/creditchain" ]]; then
          echo "is-creditchain=true" >> $GITHUB_OUTPUT
        else
          echo "is-creditchain=false" >> $GITHUB_OUTPUT
        fi
        echo "Calling repo: ${{ github.repository }}"
    - name: Cancel the workflow if the calling repo is not CreditChain
      if: ${{ inputs.cancel-workflow == 'true' && steps.determine-repo.outputs.is-creditchain == 'false' }}
      shell: bash
      run: |
        echo "Canceling workflow because the calling repo is not CreditChain"
        gh run cancel ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ inputs.token }} # this is required for gh commands to work https://cli.github.com/manual/gh_help_environment
